-- Script to delete all receipts and payments and cash closes
-- WARNING: never use on a productive environment!!!
DELETE FROM TICKETLINES;
DELETE FROM TAXLINES;
DELETE FROM TICKETS;
DELETE FROM PAYMENTS;
DELETE FROM RECEIPTS;
DELETE FROM SHAREDTICKETS;
DELETE FROM STOCKDIARY;
DELETE FROM CLOSEDCASH;
DELETE FROM STOCKCURRENT;
UPDATE CUSTOMERS SET CURDATE = NULL;
UPDATE CUSTOMERS SET CURDEBT = 0;
-- If you want also reset the receipt number counters
ALTER SEQUENCE TICKETSNUM RESTART WITH 1;
ALTER SEQUENCE TICKETSNUM_REFUND RESTART WITH 1;
ALTER SEQUENCE TICKETSNUM_PAYMENT RESTART WITH 1;
